---
name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    name: CI
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        otp: [24, 25, 26]
        mysql_version:
          - "8.4"
          - "5.7"
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: 3.20.0
      - run: |
          export MYSQL_VERSION=${{ matrix.mysql_version }}
          ./.ci/prep.sh
      - run: |
          make tests
